Усовершенствовал трекер задач.
ViktorSalk/java-kanban pull request #1
Opened 2024-10-30 16:14 UTC by ViktorSalk

2024-10-30 20:28 UTC, afomkina requested changes
Нужно поправить структуру пакетов она должна быть следующей

```
src->
    main ->
        java ->
            manager     
            task
            history
    test ->
        java -> 
            manager
            task
            history
```

2024-10-30 20:28 UTC, afomkina commented on src/main/java/manager/history/InMemoryHistoryManager.java
> +        Node prev;
У полей класса должен быть модификатор доступа

2024-10-30 20:28 UTC, afomkina commented on src/main/java/manager/history/InMemoryHistoryManager.java
> +        Task task;
Поле должно быть final

2024-10-30 20:28 UTC, afomkina commented on src/main/java/Main.java
> +        taskManager.getTaskById(task1.getId());
Класс `TaskManager` нужно удалить из проекта и использовать "фабрику" `Managers`  метод `getDefault()` для создания экземпряра класса `InMemoryHistoryManager`

2024-10-30 20:28 UTC, afomkina commented on test/java/manager/history/task/manager/InMemoryTaskManagerTest.java
> +        TaskManager taskManager = Managers.getDefault();
Повторяющееся создание менеджера нужно вынести в переменные класса или метод [@BeforeEach](https://www.geeksforgeeks.org/junit-5-beforeeach/)

2024-10-30 20:28 UTC, afomkina commented on test/java/manager/history/task/manager/InMemoryTaskManagerTest.java
> +    void testHistoryManagerWithDuplicates() {
Тесты для проверкии испотрии нужно вынести в отдельный класс, чтобы не раздувать тесты по проверки логики менеджера задач

2024-10-30 21:30 UTC, afomkina commented on src/main/java/manager/history/task/manager/InMemoryTaskManager.java
Метод `historyManager.remove(id)`; также должен использоваться в методах очищения задач по типам

2024-10-31 18:40 UTC, afomkina commented
UPD по структуре пакетов. Заметила, что тесты завязаны на местоположении папки test. Чтобы починить, структура должна быть следующей:
```
src ->
    history
    manager
    task
test ->
    history
    manager
    task
```

2024-10-31 18:46 UTC, ViktorSalk commented on src/main/java/manager/history/InMemoryHistoryManager.java
> +        Node prev;
Спасибо. Добавил модификаторы доступа в поля  `Node next и Node prev.

2024-10-31 18:47 UTC, ViktorSalk commented on src/main/java/manager/history/InMemoryHistoryManager.java
> +        Task task;
В Классе Node поле Task; теперь объявлено как "final" для обеспечения неизменности.

2024-10-31 18:47 UTC, ViktorSalk commented on src/main/java/Main.java
> +        taskManager.getTaskById(task1.getId());
Удалил класс `TaskManager` экземпляр теперь создается с использованием метода `Managers.getDefault()`.

2024-10-31 18:48 UTC, ViktorSalk commented on test/java/manager/history/task/manager/InMemoryTaskManagerTest.java
> +        TaskManager taskManager = Managers.getDefault();
Введен метод настройки "@beforeEach" в классе "InMemoryTaskManagerTest" и "HistoryTest".

2024-10-31 18:49 UTC, ViktorSalk commented on test/java/manager/history/task/manager/InMemoryTaskManagerTest.java
> +    void testHistoryManagerWithDuplicates() {
Вывел в отдельный класс "HistoryTest" тесты для проверки истории.

2024-10-31 18:51 UTC, ViktorSalk commented on src/main/java/manager/history/task/manager/InMemoryTaskManager.java
Добавлены вызовы "historyManager.remove(id)" в методах "clearTasks", "clearEpics" и "clearSubtasks" в классе "InMemoryTaskManager".

2024-10-31 19:48 UTC, afomkina requested changes

2024-10-31 19:48 UTC, afomkina commented on src/main/java/history/InMemoryHistoryManager.java
> +        Node prev; // Добавлен модификатор доступа
Нужно добавить модификатор доступа `private` для полей с 70 по 72 строку

2024-10-31 19:48 UTC, afomkina commented on src/main/java/history/InMemoryHistoryManager.java
> +                tail = newNode;
tail = newNode; является общей частью для обоих условий, нужно ее вынести за пределы проверки после 32 строки

2024-10-31 19:48 UTC, afomkina commented on test/java/manager/InMemoryTaskManagerTest.java
> +    private HistoryManager historyManager;
Этот объект не используется в тесте, его нужно удалить

2024-10-31 19:50 UTC, afomkina commented
Нечаянно в трекере поставила не ту оценку, с проектом все хорошо, он работает и выглядит здорово, нужно немного поправить

2024-11-01 14:33 UTC, ViktorSalk commented on src/main/java/history/InMemoryHistoryManager.java
> +        Node prev; // Добавлен модификатор доступа
Спасибо) Добавил модификаторы доступа private для Task tsak, Nod next, Node prev.

2024-11-01 14:35 UTC, ViktorSalk commented on src/main/java/history/InMemoryHistoryManager.java
> +                tail = newNode;
Убрал дубли выведя tail = newNode; за пределы проверки.

2024-11-01 14:36 UTC, ViktorSalk commented on test/java/manager/InMemoryTaskManagerTest.java
> +    private HistoryManager historyManager;
Удалил неиспользуемые переменные в In Memory TaskManagerTest, по аналогии убрал неиспользуемые импорты в EpicTest, HistoryTest, InMemoryTaskManagerTest.

2024-11-02 16:38 UTC, afomkina approved these changes

2024-11-07 05:48 UTC, merged