Создал ветку sprint_7-solution-in-file-manager
ViktorSalk/java-kanban pull request #2
Opened 2024-11-10 17:48 UTC by ViktorSalk

2024-11-11 14:23 UTC, afomkina requested changes

2024-11-11 14:23 UTC, afomkina commented on test/java/manager/FileBackedTaskManagerTest.java
> +    private final File tempFile = new File("temp_tasks.csv");
Нужно использовать `File.createTempFile`

2024-11-11 14:23 UTC, afomkina commented on .idea/misc.xml
Сейчас в работе есть лишние файлы, которые генерируются средой разработки, чтобы от них избавиться в файл `.gitignore` нужно добавить следующие строки:

```
.idea
```

Затем нужно будет удалить лишние папки `.idea` [из репозитория](https://docs.github.com/ru/repositories/working-with-files/managing-files/deleting-files-in-a-repository)

2024-11-11 14:23 UTC, afomkina commented on src/main/java/manager/FileBackedTaskManager.java
> +    public static void main(String[] args) throws IOException {
По тз нужно реализовать следующий сценарий:

```
Заведите несколько разных задач, эпиков и подзадач.
Создайте новый FileBackedTaskManager-менеджер из этого же файла.
Проверьте, что все задачи, эпики, подзадачи, которые были в старом менеджере, есть в новом.
```

2024-11-12 18:25 UTC, ViktorSalk commented on test/java/manager/FileBackedTaskManagerTest.java
> +    private final File tempFile = new File("temp_tasks.csv");
Для тестирования методов, использовал File.createTempFile.

2024-11-12 18:27 UTC, ViktorSalk commented on src/main/java/manager/FileBackedTaskManager.java
> +    public static void main(String[] args) throws IOException {
Реализовал пользовательский сценарий по ТЗ: завел несколько разных задач, эпиков и подзадач, создал новый FileBackedTaskManager менеджер из этого же файла и проверил: совпадают ли задачи эпики и подзадачи в первом и новом менеджере.

2024-11-12 18:29 UTC, ViktorSalk commented on .idea/misc.xml
Добавил в .gitignore  .idea и удалил misc.xml из репозитория.

2024-11-13 16:25 UTC, afomkina approved these changes

2024-11-15 14:58 UTC, merged