1) Создал ветку sprint_8-solution-time-and-duration
ViktorSalk/java-kanban pull request #3
Opened 2024-11-24 14:25 UTC by ViktorSalk

1) Добавил новую функциональность: трекер задач ожет расставлять задачи по приоритету и проверять, не пересекаются ли они по времени выполнения.

2) Добавил новые поля и методы в задачи: duration, LocalDateTime, getEndTime(). 3) Добавил валидацию во время создания или изменения задач и подзадач. 4) Добавил тесты.
5) Добавил базовый класс TaskManager с тестами для InMemoryTaskManager и FileBackedTaskManager 6) Добавил тесты HistoryManagerTest для HistoryManager 7) Использовал тип Optional, чтобы возвращать результат методов поиска задачи/подзадачи по id. 8) Добавил тесты InMemoryTaskManager для новой фичи по Optional.

2024-11-24 15:29 UTC, afomkina requested changes

2024-11-24 15:29 UTC, afomkina commented on src/main/java/manager/FileBackedTaskManager.java
>                      } else if (task instanceof Subtask) {
Нужно избавиться от instanceof, так как он не соответствует парадигме ООП. Для этого нужно использовать enum с типом задач

2024-11-24 15:29 UTC, afomkina commented on src/main/java/history/HistoryManagerImpl.java
> +        if (task != null && !history.stream().anyMatch(t -> t.getId() == task.getId())) {
- Лучше использовать `noneMatch` вместо инверсии с `anyMatch`
- Нужно переименовать однобуквенную переменную

2024-11-24 15:29 UTC, afomkina commented on src/main/java/manager/FileBackedTaskManager.java
>          if (task instanceof Subtask) {
Нужно избавиться от instanceof, так как он не соответствует парадигме ООП. Для этого нужно использовать enum с типом задач

2024-11-24 15:29 UTC, afomkina commented on test/java/history/HistoryManagerTest.java
> +public class HistoryManagerTest {
Предлагаю немного подекомпозировать тесты и разбить из на логические составляющие. Это можно сделать с помощью [@Nested классов](https://www.petrikainulainen.net/programming/testing/junit-5-tutorial-writing-nested-tests/). Так код станет более читаемым и его будет проще поддерживать

2024-11-24 15:29 UTC, afomkina commented on test/java/history/HistoryManagerTest.java
> +        Task task1 = new Task("Задача 1", "Описание 1");
Нужно максимально избавиться от дублирований в тесте. Создание  повторяющихся объектов задач, предлагаю вынести в отдельный утильный класс и сделать статическим методом (assignTask, assignEpic...), чтобы его можно быть переиспользовать в каждом из тестов

2024-11-24 15:29 UTC, afomkina commented on test/java/manager/InMemoryTaskManagerTest.java
> +        return new InMemoryTaskManager();
Должен создаваться с помощью фабрики Managers

2024-11-24 15:29 UTC, afomkina commented on test/java/manager/InMemoryTaskManagerTest.java
> +    public void setUp() {
Этот метод нужно удалить так как присвоение происходит в `TaskManagerTest`

2024-11-24 15:29 UTC, afomkina commented on test/java/manager/InMemoryTaskManagerTest.java
>      }
Все общие тесты, которые есть в классе ниже должны находиться в `TaskManagerTest`, отсюда их нужно удалить

2024-11-25 19:36 UTC, ViktorSalk commented on src/main/java/manager/FileBackedTaskManager.java
>                      } else if (task instanceof Subtask) {
В FileBackedTaskManager избавился от instanceof. Использовал enum с типом задач.

2024-11-25 19:37 UTC, ViktorSalk commented on src/main/java/history/HistoryManagerImpl.java
> +        if (task != null && !history.stream().anyMatch(t -> t.getId() == task.getId())) {
В HistoryManagerImpl использовал noneMatch вместо инверсии с anyMatch, переименовал однобуквенную переменную в existingTask.

2024-11-25 19:37 UTC, ViktorSalk commented on test/java/history/HistoryManagerTest.java
> +public class HistoryManagerTest {
Декомпозировал тесты и разбил их на логические составляющие.

2024-11-25 19:38 UTC, ViktorSalk commented on test/java/history/HistoryManagerTest.java
> +        Task task1 = new Task("Задача 1", "Описание 1");
Спасибо =)) Убрал дублирования в тесте.

2024-11-25 19:38 UTC, ViktorSalk commented on test/java/manager/InMemoryTaskManagerTest.java
> +        return new InMemoryTaskManager();
В HistoryManagerTest новые экземпляры создаются с помощью фабрики Managers

2024-11-25 19:38 UTC, ViktorSalk commented on test/java/manager/InMemoryTaskManagerTest.java
> +    public void setUp() {
В InMemoryTaskManagerTest удалил setUp так как присвоение происходит в TaskManagerTest.

2024-11-25 19:39 UTC, ViktorSalk commented on test/java/manager/InMemoryTaskManagerTest.java
>      }
Удалил лишние тесты уже имеющиеся в TaskManagerTest

2024-11-25 19:41 UTC, ViktorSalk commented on src/main/java/manager/FileBackedTaskManager.java
>          if (task instanceof Subtask) {
В FileBackedTaskManager избавился от instanceof. Использовал enum.

2024-11-26 00:16 UTC, afomkina requested changes

2024-11-26 00:16 UTC, afomkina commented on test/java/history/HistoryManagerTest.java
> +    class AddTaskTests { // Тесты добавления задач в историю
👍

2024-11-26 00:16 UTC, afomkina commented on test/java/manager/TimeSlotManagerTest.java
> +    private InMemoryTaskManager taskManager;
Должен быть интерфейсом `TaskManager`

2024-11-26 00:16 UTC, afomkina commented on test/java/manager/TimeSlotManagerTest.java
> +        taskManager = new InMemoryTaskManager();
Должен создаваться с помощью метода из фабрики `Managers`

2024-11-26 00:16 UTC, afomkina commented on src/main/java/manager/Managers.java
> +    public static InMemoryTaskManager getInMemoryTaskManager() {
Есть метод `getDefault`, который возвращает `InMemoryTaskManager`, нужно использовать его, а этот метод удалить

2024-11-26 17:36 UTC, ViktorSalk commented on test/java/manager/TimeSlotManagerTest.java
> +    private InMemoryTaskManager taskManager;
Изменил тип на TaskManager

2024-11-26 17:37 UTC, ViktorSalk commented on test/java/manager/TimeSlotManagerTest.java
> +        taskManager = new InMemoryTaskManager();
Заменил, теперь в setUp новые экземпляры создаются с помощью фабрики Managers

2024-11-26 17:37 UTC, ViktorSalk commented on src/main/java/manager/Managers.java
> +    public static InMemoryTaskManager getInMemoryTaskManager() {
Удалил getInMemoryTaskManager оставив метод getDefault, возвращающий InMemoryTaskManager.

2024-11-27 16:24 UTC, afomkina approved these changes

2024-12-01 14:43 UTC, merged