Реализовал API, в котором эндпоинты соответствовуют вызовам базовых методов интерфейса TaskManager.
ViktorSalk/java-kanban pull request #4
Opened 2024-12-08 15:46 UTC by ViktorSalk

1) Создал класс HttpTaskServer — он будет слушать порт 8080 и принимать запросы. 
2) Создал класс обработчик BaseHttpHandler
3) Создал класс DurationAdapter для сериализации и десериализации объектов Duration. 
4) Создал key-value сервер для хранения данных.
5) Создал классы TaskHandler, SubtaskHandler, EpicHandler, для обработки HTTP-запросов для разных типов задач. 
6) Создал классы HistoryHandler, PrioritizedHandler для обработки HTTP-запросов в работе с историей просмотров и приоритезацией задач 
7) Сделал тесты по новым классам для различных сценариев.

2024-12-09 14:00 UTC, afomkina requested changes

2024-12-09 14:00 UTC, afomkina commented on src/main/java/history/HistoryHandler.java
> +                sendResponse(exchange, "{\"error\": \"Method not allowed\"}", 405);
Задание со `"*"`:
Можно создать отдельное перечисление для HTTP кодов и использовать его вместо "голых" цифр. 
Так код будет выглядеть более читаемо и понятней. 
Примеры можно посмотреть в главе [Конструкторы, поля и методы перечисления](https://metanit.com/java/tutorial/3.8.php#:~:text=%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80%D1%8B%2C%20%D0%BF%D0%BE%D0%BB%D1%8F%20%D0%B8%20%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B%20%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F)

2024-12-09 14:00 UTC, afomkina commented on src/main/java/history/HistoryHandler.java
> +            e.printStackTrace();
Печатать стек трейс обычно изличшне, лучше более точно настроить логирование

2024-12-09 14:00 UTC, afomkina commented on src/main/java/history/HistoryHandler.java
> +        } catch (Exception e) {
Нужно переименовать однобуквенные переменные в коде

2024-12-09 14:00 UTC, afomkina commented on src/main/java/history/HistoryHandler.java
> +        try {
Лучше использовать [try with resources](https://javarush.com/quests/lectures/questsyntaxpro.level15.lecture00), чтобы не забывать закрывать поток в конце работы

2024-12-09 14:00 UTC, afomkina commented on src/main/java/manager/InMemoryTaskManager.java
>      public Optional<Subtask> getSubtaskByIdOptional(int id) {
Нужно удалить все методы, которые возвращают `Optional`, они лишние

2024-12-09 14:00 UTC, afomkina commented on src/main/java/manager/KVServer.java
> +public class KVServer {
Этот класс нужно использовать

2024-12-09 14:00 UTC, afomkina commented on src/main/java/manager/KVServer.java
> +        try {
Нужно использовать try with resources

2024-12-09 14:00 UTC, afomkina commented on src/main/java/manager/KVServer.java
> +        try {
Нужно использовать try with resources

2024-12-09 14:00 UTC, afomkina commented on src/main/java/manager/KVServer.java
> +        try {
Нужно использовать try with resources

2024-12-09 14:00 UTC, afomkina commented on src/main/java/manager/KVServer.java
> +        return new String(h.getRequestBody().readAllBytes(), "UTF-8");
Лучше использовать встроенную константу `StandardCharsets.UTF_8`

2024-12-09 14:00 UTC, afomkina commented on src/main/java/manager/KVServer.java
> +        byte[] resp = text.getBytes("UTF-8");
Лучше использовать встроенную константу `StandardCharsets.UTF_8`

2024-12-09 14:00 UTC, afomkina commented on src/main/java/task/EpicHandler.java
> +            e.printStackTrace();
Печатать стектрейс не нужно

2024-12-09 14:00 UTC, afomkina commented on src/main/java/task/EpicHandler.java
> +        try {
Используй try with resources здесь и ниже

2024-12-09 14:00 UTC, afomkina commented on src/main/java/task/PrioritizedHandler.java
> +            e.printStackTrace();
Печатать стектрейс не нужно

2024-12-09 14:00 UTC, afomkina commented on src/main/java/task/SubtaskHandler.java
> +            e.printStackTrace();
Печатать стектрейс не нужно

2024-12-09 14:00 UTC, afomkina commented on src/main/java/task/TaskHandler.java
> +        try {
Код со строк 25-47 повторяется в классах `EpicHandler` и `SubtaskHandler`, нужно избавиться от дублирования

2024-12-10 09:19 UTC, ViktorSalk commented on src/main/java/history/HistoryHandler.java
> +                sendResponse(exchange, "{\"error\": \"Method not allowed\"}", 405);
Спасибо) 
Создал отдельное перечисление для HTTP-кодов и использовать его вместо «голых» цифр в задачх, подзадачах, эпиках, приоритетах.

2024-12-10 09:19 UTC, ViktorSalk commented on src/main/java/history/HistoryHandler.java
> +            e.printStackTrace();
Убрал лишний стек-трейсинг.

2024-12-10 09:20 UTC, ViktorSalk commented on src/main/java/task/EpicHandler.java
> +            e.printStackTrace();
Убрал лишний стек-трейсинг.

2024-12-10 09:20 UTC, ViktorSalk commented on src/main/java/task/PrioritizedHandler.java
> +            e.printStackTrace();
Убрал лишний стек-трейсинг.

2024-12-10 09:20 UTC, ViktorSalk commented on src/main/java/task/SubtaskHandler.java
> +            e.printStackTrace();
Убрал лишний стек-трейсинг.

2024-12-10 09:21 UTC, ViktorSalk commented on src/main/java/history/HistoryHandler.java
> +        } catch (Exception e) {
Переименовал однобуквенные переменные в коде.

2024-12-10 09:21 UTC, ViktorSalk commented on src/main/java/history/HistoryHandler.java
> +        try {
Использовал try with resources.

2024-12-10 09:22 UTC, ViktorSalk commented on src/main/java/manager/KVServer.java
> +        try {
Использовал try with resources, чтобы не забывать закрывать поток в конце работы.

2024-12-10 09:22 UTC, ViktorSalk commented on src/main/java/manager/KVServer.java
> +        try {
Использовал try with resources.

2024-12-10 09:22 UTC, ViktorSalk commented on src/main/java/manager/KVServer.java
> +        try {
Использовал try with resources.

2024-12-10 09:23 UTC, ViktorSalk commented on src/main/java/task/EpicHandler.java
> +        try {
Использовал try with resources в EpicHandler.

2024-12-10 09:24 UTC, ViktorSalk commented on src/main/java/manager/InMemoryTaskManager.java
>      public Optional<Subtask> getSubtaskByIdOptional(int id) {
Удалил все методы, которые возвращают Optional.

2024-12-10 09:24 UTC, ViktorSalk commented on src/main/java/manager/KVServer.java
> +public class KVServer {
Реализовал KVServer и затестил в TaskEndpointTest

2024-12-10 09:25 UTC, ViktorSalk commented on src/main/java/manager/KVServer.java
> +        return new String(h.getRequestBody().readAllBytes(), "UTF-8");
Использовал встроенную константу StandardCharsets.UTF_8.

2024-12-10 09:25 UTC, ViktorSalk commented on src/main/java/manager/KVServer.java
> +        byte[] resp = text.getBytes("UTF-8");
Использовал встроенную константу StandardCharsets.UTF_8.

2024-12-10 09:27 UTC, ViktorSalk commented on src/main/java/task/TaskHandler.java
> +        try {
Избавился от дублирования создав абстрактный класс AbstractTaskHandler и унаследовал handle из него.

2024-12-10 14:23 UTC, afomkina approved these changes

2024-12-10 14:23 UTC, afomkina commented on src/main/java/http/HttpStatusCode.java
> +public enum HttpStatusCode {
Клево, что сделал дополнительное задание, молодец 👍

2024-12-10 16:24 UTC, ViktorSalk commented on src/main/java/http/HttpStatusCode.java
> +public enum HttpStatusCode {
Спасибо =)

2024-12-10 16:25 UTC, merged